---

- name: Copy docker resources to the server
  copy:
    src: ./../../../src/website
    dest: /home/{{ ansible_user }}

- name: Create data folder for wordpress
  file:
    path: /home/cloud1/data/wp
    state: directory
    recurse: yes



