version: '3.1'

services:
  mariadb:
    container_name: database-mariadb
    build: mariadb
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    restart: on-failure

networks:
  net2:
    driver: bridge

volumes:
  db:
    driver_opts :
      type : 'none'
      o : bind
      device : /home/${USER}/data/db