version: '3.1'

services:
  nginx:
    container_name: nginx
    build: nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - net1
    volumes:
      - wp:/var/www/html
    restart: on-failure

  wordpress:
    container_name: wordpress
    build: wordpress
    networks:
      - net1
    volumes:
      - wp:/var/www/html
    env_file:
      - .env
    restart: on-failure

networks:
  net1:
    driver: bridge
    
volumes:
  wp:
    driver_opts :
      type : 'none'
      o : bind
      device : /home/cloud1/data/wp
