version: '3.1'

services:
  nginx:
    container_name: nginx
    build: nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - net1
    volumes:
      - wp:/var/www/html
      - ./logs/nginx:/var/log/nginx
    restart: on-failure

  wordpress:
    container_name: wordpress
    build: wordpress
    networks:
      - net1
    volumes:
      - wp:/var/www/html
      - ./logs/wordpress:/var/www/html/wp-content/logs
    env_file:
      - .env
    restart: on-failure

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.10.0
    container_name: filebeat
    volumes:
      - ./logs/nginx:/var/log/nginx 
      - ./logs/wordpress:/var/www/html/wp-content/logs  
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml  
    environment:
      - "ELASTICSEARCH_HOSTS=10.0.3.2:9200"
    command: ["--strict.perms=false"]

networks:
  net1:
    driver: bridge
    
volumes:
  wp:
    driver_opts :
      type : 'none'
      o : bind
      device : /home/cloud1/data/wp
