version: '3.1'

services:
  nginx:
    container_name: nginx
    build: nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - net1
    volumes:
      - wp:/var/www/html
    restart: on-failure

  wordpress:
    container_name: wordpress
    build: wordpress
    networks:
      - net1
    volumes:
      - wp:/var/www/html
    environment:
      - URL="EURL"
      - WORDPRESS_ROOT_LOGIN="WRL"
      - DB_ROOT_PASSWORD="DRP"
      - DB_USER="EDU"
      - DB_PASSWORD="EDP"
    restart: on-failure

networks:
  net1:
    driver: bridge
    
volumes:
  wp:
    driver_opts :
      type : 'none'
      o : bind
      device : /home/cloud1/data/wp
