---
- name: Check if Docker is already installed
  shell: "docker --version"
  register: docker_installed
  ignore_errors: true
  changed_when: false

- name: Add Docker GPG key
  apt_key:
    url: "{{ DOCKER_GPT_UBUNTU }}"
    state: present 
  when: docker_installed.rc != 0

- name: Add Docker repository
  apt_repository:
    repo: "deb {{ DOCKER_REPO_UBUNTU }} jammy stable"
  when: docker_installed.rc != 0

- name: Update apt cache
  apt:
    update_cache: yes
  when: docker_installed.rc != 0

- name: Install Docker engine
  apt: 
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: latest
  when: docker_installed.rc != 0
  
- name: Install python docker
  pip:
    name: 
      - docker
      - docker-compose
    state: present
  # when: docker_installed.rc != 0
